[package]
name = "visual_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
waldo_vision = { path = "../waldo_vision" }
opencv = { version = "0.88.8", default-features = false, features = ["videoio", "highgui", "imgproc"] }